feat: :sparkles: add `examples` directory with .gitmodules
saleor/app-sdk pull request #285
Opened 2023-09-08 12:47 UTC by peelar

2023-09-23 07:37 UTC, lkostrowski commented
@peelar in general I like the idea, but I don't like that coupling

SDK depends on app-template, that contains SDK usage, on app-template branches, to mention this in SDK repo.

I think we should somehow move app-template code from app-template to app-sdk and keep them entirely here. Maybe submodules, maybe not, just I'd not decouple them.

2023-09-23 07:37 UTC, lkostrowski requested changes
Please figure out decoupling from app-template repo

2023-10-11 07:56 UTC, lkostrowski commented
@peelar please hand over to @saleor/dex team

2023-10-11 09:12 UTC, mmiszy commented
Do we even need app-sdk examples if apps are open source already?

2023-10-11 09:48 UTC, lkostrowski commented
> Do we even need app-sdk examples if apps are open source already?

IMO yes but if DX team decides not to have them, we can remove them. 

I don't think apps are good examples because apps are complex and contain a lot of logic that hides what comes from SDK. Examples are just barebones app-template + app-sdk method applied on top. Very visible.

If we don't want to have examples to maintain, we should probably add more docs with examples written as snippets. Or - a code sandbox?

2025-03-13 10:52 UTC, closed without merging