add RedisAPL
saleor/app-sdk pull request #287
Opened 2023-09-30 18:23 UTC by djkato

Will fail tests on PRs / Github actions, as it requires a local redis server obviously. But they pass when I test them :)

2023-09-30 18:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/saleor/app-sdk?pullRequest=287) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/saleor/app-sdk?pullRequest=287) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/saleor/app-sdk?pullRequest=287) it.</sub>

2023-09-30 19:41 UTC, djkato commented
This PR relies on the APP ID to be passed through the constructor.
When trying to implement this for an actual app - specifically mails and messages, I noticed that I've no clue where to get the appID from. Is it even obtainable?

2023-10-02 07:51 UTC, lkostrowski requested changes

2023-10-02 07:51 UTC, lkostrowski commented on .changeset/honky-dory-fox.md
> +- npm run lint changed a lot of files, guess it wasn't ran in a while :)
Thanks for a notice, but its not a changelog message and I don't see any linter changes committed, so we can remove this message

2023-10-02 07:51 UTC, lkostrowski commented on src/APL/redis-apl.test.ts
> +const localRedisServerUrl = new URL("redis://127.0.0.1:6379/1");
Redis address should come from ENV (.env.test can be introduced)

2023-10-02 07:51 UTC, lkostrowski commented on src/APL/redis-apl.test.ts
> +// Obviously, for this test to pass you need to have a docker container running redis :)
In units tests we will not have Redis available so you need to mock it, otherwise your PR will kill CICD until we rework infrastructure

2023-10-02 07:51 UTC, lkostrowski commented on src/APL/redis-apl.ts
> +const debug = createAPLDebug("UpstashAPL");
RedisAPL

2023-11-29 17:47 UTC, closed without merging

2023-11-29 17:47 UTC, lkostrowski commented
stale, closing